### ISSUE TITLE
1.0.0.3 - distance regression

### ISSUE THREAD

**Issue by LukasJK** [Erabior/ShortFused#2]
Hey,
It seems with 1.0.3 the distances are back to default - had no issues with 1.0.0.2
![image](https://github.com/Erabior/ShortFused/assets/14063669/a8df9e9c-a42d-4d2d-b613-987b303cb3cc)

Beepinex log shows that the dll was loaded fine.

**Comment by Erabior** [comment]
I think I know what's going on here. Its very possible I uploaded the incorrect file. I apologize for any inconvenience.

**Comment by Erabior** [comment]
fixed with [version 1.0.1.0](https://github.com/Erabior/ShortFused/releases/tag/1.0.1.0)
